#!/usr/bin/env python3
import json

# Read existing names
with open('/Users/jdecker/projects/ios/name/NameMatch/Resources/names.json', 'r') as f:
    existing_names = json.load(f)

# Create comprehensive lists by category
male_names = [
    # A
    {"id": "aaron", "name": "Aaron", "gender": "male", "origins": ["hebrew"], "styles": ["biblical", "classic"], "meaning": "Mountain of strength", "popularity": "popular"},
    {"id": "abbott", "name": "Abbott", "gender": "male", "origins": ["english"], "styles": ["vintage", "strong"], "meaning": "Father", "popularity": "rare"},
    {"id": "abel", "name": "Abel", "gender": "male", "origins": ["hebrew"], "styles": ["biblical", "classic"], "meaning": "Breath", "popularity": "uncommon"},
    {"id": "abner", "name": "Abner", "gender": "male", "origins": ["hebrew"], "styles": ["biblical", "vintage"], "meaning": "Father of light", "popularity": "rare"},
    {"id": "ace", "name": "Ace", "gender": "male", "origins": ["latin"], "styles": ["modern", "strong"], "meaning": "Number one", "popularity": "uncommon"},
    {"id": "achilles", "name": "Achilles", "gender": "male", "origins": ["greek"], "styles": ["mythological", "strong"], "meaning": "Warrior", "popularity": "rare"},
    {"id": "adam", "name": "Adam", "gender": "male", "origins": ["hebrew"], "styles": ["biblical", "classic"], "meaning": "Man, earth", "popularity": "popular"},
    {"id": "addison", "name": "Addison", "gender": "neutral", "origins": ["english"], "styles": ["modern", "trendy"], "meaning": "Son of Adam", "popularity": "popular"},
    {"id": "adonis", "name": "Adonis", "gender": "male", "origins": ["greek"], "styles": ["mythological", "strong"], "meaning": "Lord", "popularity": "uncommon"},
    {"id": "adrian", "name": "Adrian", "gender": "male", "origins": ["latin"], "styles": ["classic", "royal"], "meaning": "From Adria", "popularity": "popular"},
    {"id": "alaric", "name": "Alaric", "gender": "male", "origins": ["german"], "styles": ["vintage", "royal"], "meaning": "Ruler of all", "popularity": "rare"},
    {"id": "alastair", "name": "Alastair", "gender": "male", "origins": ["scottish"], "styles": ["classic", "strong"], "meaning": "Defender of men", "popularity": "uncommon"},
    {"id": "albert", "name": "Albert", "gender": "male", "origins": ["german"], "styles": ["vintage", "royal"], "meaning": "Noble, bright", "popularity": "common"},
    {"id": "alec", "name": "Alec", "gender": "male", "origins": ["greek"], "styles": ["classic", "strong"], "meaning": "Defender", "popularity": "common"},
    {"id": "alfred", "name": "Alfred", "gender": "male", "origins": ["english"], "styles": ["vintage", "royal"], "meaning": "Wise counselor", "popularity": "uncommon"},
    {"id": "alistair", "name": "Alistair", "gender": "male", "origins": ["scottish"], "styles": ["classic", "royal"], "meaning": "Defender", "popularity": "uncommon"},
    {"id": "ambrose", "name": "Ambrose", "gender": "male", "origins": ["greek"], "styles": ["vintage", "literary"], "meaning": "Immortal", "popularity": "rare"},
    {"id": "amos", "name": "Amos", "gender": "male", "origins": ["hebrew"], "styles": ["biblical", "vintage"], "meaning": "Carried by God", "popularity": "uncommon"},
    {"id": "anders", "name": "Anders", "gender": "male", "origins": ["scandinavian"], "styles": ["modern", "strong"], "meaning": "Strong and manly", "popularity": "uncommon"},
    {"id": "andre", "name": "Andre", "gender": "male", "origins": ["french"], "styles": ["classic", "strong"], "meaning": "Manly", "popularity": "common"},
    {"id": "angus", "name": "Angus", "gender": "male", "origins": ["scottish"], "styles": ["vintage", "strong"], "meaning": "One strength", "popularity": "uncommon"},
    {"id": "apollo", "name": "Apollo", "gender": "male", "origins": ["greek"], "styles": ["mythological", "strong"], "meaning": "Destroyer", "popularity": "uncommon"},
    {"id": "archer", "name": "Archer", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Bowman", "popularity": "uncommon"},
    {"id": "arden", "name": "Arden", "gender": "neutral", "origins": ["english"], "styles": ["nature", "literary"], "meaning": "Great forest", "popularity": "uncommon"},
    {"id": "ari", "name": "Ari", "gender": "neutral", "origins": ["hebrew"], "styles": ["modern", "gentle"], "meaning": "Lion", "popularity": "common"},
    {"id": "arlo", "name": "Arlo", "gender": "male", "origins": ["english"], "styles": ["modern", "artistic"], "meaning": "Fortified hill", "popularity": "popular"},
    {"id": "armando", "name": "Armando", "gender": "male", "origins": ["spanish"], "styles": ["classic", "strong"], "meaning": "Soldier", "popularity": "common"},
    {"id": "arnold", "name": "Arnold", "gender": "male", "origins": ["german"], "styles": ["vintage", "strong"], "meaning": "Eagle power", "popularity": "uncommon"},
    {"id": "artemis", "name": "Artemis", "gender": "neutral", "origins": ["greek"], "styles": ["mythological", "nature"], "meaning": "Safe", "popularity": "rare"},
    {"id": "ash", "name": "Ash", "gender": "neutral", "origins": ["english"], "styles": ["nature", "modern"], "meaning": "Ash tree", "popularity": "uncommon"},
    {"id": "ashton", "name": "Ashton", "gender": "neutral", "origins": ["english"], "styles": ["modern", "trendy"], "meaning": "Ash tree town", "popularity": "popular"},
    {"id": "atlas", "name": "Atlas", "gender": "male", "origins": ["greek"], "styles": ["mythological", "strong"], "meaning": "Bearer of the heavens", "popularity": "uncommon"},
    {"id": "atticus", "name": "Atticus", "gender": "male", "origins": ["latin"], "styles": ["literary", "classic"], "meaning": "From Attica", "popularity": "common"},
    {"id": "aubrey", "name": "Aubrey", "gender": "neutral", "origins": ["french"], "styles": ["vintage", "gentle"], "meaning": "Elf ruler", "popularity": "popular"},
    {"id": "august", "name": "August", "gender": "male", "origins": ["latin"], "styles": ["vintage", "royal"], "meaning": "Great, magnificent", "popularity": "common"},
    {"id": "austin", "name": "Austin", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Great", "popularity": "popular"},
    {"id": "avery", "name": "Avery", "gender": "neutral", "origins": ["english"], "styles": ["modern", "gentle"], "meaning": "Ruler of elves", "popularity": "popular"},
    {"id": "axel", "name": "Axel", "gender": "male", "origins": ["scandinavian"], "styles": ["modern", "strong"], "meaning": "Father of peace", "popularity": "popular"},
    {"id": "axton", "name": "Axton", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Sword stone", "popularity": "uncommon"},
    {"id": "ayden", "name": "Ayden", "gender": "male", "origins": ["irish"], "styles": ["modern", "strong"], "meaning": "Little fire", "popularity": "common"},

    # B
    {"id": "barnaby", "name": "Barnaby", "gender": "male", "origins": ["hebrew"], "styles": ["vintage", "gentle"], "meaning": "Son of consolation", "popularity": "rare"},
    {"id": "barrett", "name": "Barrett", "gender": "male", "origins": ["german"], "styles": ["modern", "strong"], "meaning": "Bear strength", "popularity": "uncommon"},
    {"id": "barron", "name": "Barron", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Nobleman", "popularity": "uncommon"},
    {"id": "bartholomew", "name": "Bartholomew", "gender": "male", "origins": ["aramaic"], "styles": ["biblical", "vintage"], "meaning": "Son of furrows", "popularity": "rare"},
    {"id": "basil", "name": "Basil", "gender": "male", "origins": ["greek"], "styles": ["vintage", "royal"], "meaning": "King", "popularity": "rare"},
    {"id": "baxter", "name": "Baxter", "gender": "male", "origins": ["english"], "styles": ["vintage", "strong"], "meaning": "Baker", "popularity": "uncommon"},
    {"id": "baylen", "name": "Baylen", "gender": "male", "origins": ["english"], "styles": ["modern", "trendy"], "meaning": "Auburn-haired", "popularity": "uncommon"},
    {"id": "beau", "name": "Beau", "gender": "male", "origins": ["french"], "styles": ["modern", "gentle"], "meaning": "Handsome", "popularity": "popular"},
    {"id": "beckett", "name": "Beckett", "gender": "male", "origins": ["english"], "styles": ["modern", "literary"], "meaning": "Bee cottage", "popularity": "popular"},
    {"id": "benedict", "name": "Benedict", "gender": "male", "origins": ["latin"], "styles": ["classic", "royal"], "meaning": "Blessed", "popularity": "uncommon"},
    {"id": "bennett", "name": "Bennett", "gender": "male", "origins": ["latin"], "styles": ["classic", "strong"], "meaning": "Blessed", "popularity": "popular"},
    {"id": "benson", "name": "Benson", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Son of Benedict", "popularity": "uncommon"},
    {"id": "bentley", "name": "Bentley", "gender": "male", "origins": ["english"], "styles": ["modern", "trendy"], "meaning": "Meadow with coarse grass", "popularity": "popular"},
    {"id": "blaine", "name": "Blaine", "gender": "male", "origins": ["scottish"], "styles": ["modern", "strong"], "meaning": "Yellow", "popularity": "uncommon"},
    {"id": "blair", "name": "Blair", "gender": "neutral", "origins": ["scottish"], "styles": ["modern", "strong"], "meaning": "Field", "popularity": "common"},
    {"id": "blake", "name": "Blake", "gender": "neutral", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Dark or pale", "popularity": "popular"},
    {"id": "bodhi", "name": "Bodhi", "gender": "male", "origins": ["indian"], "styles": ["bohemian", "spiritual"], "meaning": "Awakening", "popularity": "common"},
    {"id": "boone", "name": "Boone", "gender": "male", "origins": ["french"], "styles": ["vintage", "strong"], "meaning": "Good", "popularity": "uncommon"},
    {"id": "bowen", "name": "Bowen", "gender": "male", "origins": ["welsh"], "styles": ["modern", "strong"], "meaning": "Son of Owen", "popularity": "uncommon"},
    {"id": "boyd", "name": "Boyd", "gender": "male", "origins": ["scottish"], "styles": ["vintage", "strong"], "meaning": "Yellow-haired", "popularity": "uncommon"},
    {"id": "braden", "name": "Braden", "gender": "male", "origins": ["irish"], "styles": ["modern", "strong"], "meaning": "Broad valley", "popularity": "common"},
    {"id": "bradley", "name": "Bradley", "gender": "male", "origins": ["english"], "styles": ["classic", "strong"], "meaning": "Broad meadow", "popularity": "popular"},
    {"id": "brady", "name": "Brady", "gender": "male", "origins": ["irish"], "styles": ["modern", "strong"], "meaning": "Spirited", "popularity": "popular"},
    {"id": "braxton", "name": "Braxton", "gender": "male", "origins": ["english"], "styles": ["modern", "trendy"], "meaning": "Brock's town", "popularity": "popular"},
    {"id": "brayden", "name": "Brayden", "gender": "male", "origins": ["irish"], "styles": ["modern", "trendy"], "meaning": "Broad valley", "popularity": "popular"},
    {"id": "brendan", "name": "Brendan", "gender": "male", "origins": ["irish"], "styles": ["classic", "strong"], "meaning": "Prince", "popularity": "common"},
    {"id": "brennan", "name": "Brennan", "gender": "male", "origins": ["irish"], "styles": ["modern", "strong"], "meaning": "Descendant of the sad one", "popularity": "common"},
    {"id": "brent", "name": "Brent", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "High place", "popularity": "common"},
    {"id": "brett", "name": "Brett", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "From Brittany", "popularity": "common"},
    {"id": "brian", "name": "Brian", "gender": "male", "origins": ["irish"], "styles": ["classic", "strong"], "meaning": "High, noble", "popularity": "popular"},
    {"id": "brice", "name": "Brice", "gender": "male", "origins": ["celtic"], "styles": ["modern", "strong"], "meaning": "Speckled", "popularity": "uncommon"},
    {"id": "briggs", "name": "Briggs", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Dweller by the bridge", "popularity": "uncommon"},
    {"id": "brock", "name": "Brock", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Badger", "popularity": "common"},
    {"id": "brody", "name": "Brody", "gender": "male", "origins": ["irish"], "styles": ["modern", "strong"], "meaning": "Ditch", "popularity": "popular"},
    {"id": "bronson", "name": "Bronson", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Son of the brown one", "popularity": "uncommon"},
    {"id": "brooks", "name": "Brooks", "gender": "male", "origins": ["english"], "styles": ["modern", "nature"], "meaning": "Of the brook", "popularity": "popular"},
    {"id": "bruce", "name": "Bruce", "gender": "male", "origins": ["scottish"], "styles": ["classic", "strong"], "meaning": "Thick brush", "popularity": "common"},
    {"id": "bruno", "name": "Bruno", "gender": "male", "origins": ["german"], "styles": ["vintage", "strong"], "meaning": "Brown", "popularity": "common"},
    {"id": "bryant", "name": "Bryant", "gender": "male", "origins": ["irish"], "styles": ["classic", "strong"], "meaning": "Strong", "popularity": "common"},
    {"id": "bryce", "name": "Bryce", "gender": "neutral", "origins": ["scottish"], "styles": ["modern", "strong"], "meaning": "Speckled", "popularity": "popular"},
    {"id": "bryson", "name": "Bryson", "gender": "male", "origins": ["english"], "styles": ["modern", "trendy"], "meaning": "Son of Brice", "popularity": "popular"},

    # C
    {"id": "cade", "name": "Cade", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Round", "popularity": "uncommon"},
    {"id": "caden", "name": "Caden", "gender": "male", "origins": ["irish"], "styles": ["modern", "trendy"], "meaning": "Fighter", "popularity": "popular"},
    {"id": "caelan", "name": "Caelan", "gender": "neutral", "origins": ["irish"], "styles": ["modern", "gentle"], "meaning": "Slender", "popularity": "uncommon"},
    {"id": "cain", "name": "Cain", "gender": "male", "origins": ["hebrew"], "styles": ["biblical", "strong"], "meaning": "Acquired", "popularity": "uncommon"},
    {"id": "cairn", "name": "Cairn", "gender": "male", "origins": ["scottish"], "styles": ["nature", "rare"], "meaning": "Mound of stones", "popularity": "rare"},
    {"id": "cairo", "name": "Cairo", "gender": "neutral", "origins": ["arabic"], "styles": ["modern", "exotic"], "meaning": "Victorious", "popularity": "uncommon"},
    {"id": "callen", "name": "Callen", "gender": "male", "origins": ["irish"], "styles": ["modern", "strong"], "meaning": "Battle", "popularity": "uncommon"},
    {"id": "callum", "name": "Callum", "gender": "male", "origins": ["scottish"], "styles": ["classic", "strong"], "meaning": "Dove", "popularity": "popular"},
    {"id": "calvin", "name": "Calvin", "gender": "male", "origins": ["latin"], "styles": ["classic", "strong"], "meaning": "Bald", "popularity": "popular"},
    {"id": "camden", "name": "Camden", "gender": "neutral", "origins": ["scottish"], "styles": ["modern", "trendy"], "meaning": "Winding valley", "popularity": "popular"},
    {"id": "cameron", "name": "Cameron", "gender": "neutral", "origins": ["scottish"], "styles": ["modern", "strong"], "meaning": "Crooked nose", "popularity": "popular"},
    {"id": "campbell", "name": "Campbell", "gender": "neutral", "origins": ["scottish"], "styles": ["modern", "strong"], "meaning": "Crooked mouth", "popularity": "uncommon"},
    {"id": "cannon", "name": "Cannon", "gender": "male", "origins": ["french"], "styles": ["modern", "strong"], "meaning": "Church official", "popularity": "uncommon"},
    {"id": "carl", "name": "Carl", "gender": "male", "origins": ["german"], "styles": ["vintage", "classic"], "meaning": "Free man", "popularity": "common"},
    {"id": "carlos", "name": "Carlos", "gender": "male", "origins": ["spanish"], "styles": ["classic", "strong"], "meaning": "Free man", "popularity": "popular"},
    {"id": "carmelo", "name": "Carmelo", "gender": "male", "origins": ["spanish"], "styles": ["classic", "strong"], "meaning": "Garden", "popularity": "uncommon"},
    {"id": "carson", "name": "Carson", "gender": "male", "origins": ["scottish"], "styles": ["modern", "strong"], "meaning": "Son of marsh-dwellers", "popularity": "popular"},
    {"id": "cash", "name": "Cash", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Hollow", "popularity": "popular"},
    {"id": "caspian", "name": "Caspian", "gender": "male", "origins": ["literary"], "styles": ["literary", "mystical"], "meaning": "White", "popularity": "uncommon"},
    {"id": "cassius", "name": "Cassius", "gender": "male", "origins": ["latin"], "styles": ["vintage", "strong"], "meaning": "Hollow", "popularity": "uncommon"},
    {"id": "cayden", "name": "Cayden", "gender": "male", "origins": ["american"], "styles": ["modern", "trendy"], "meaning": "Fighter", "popularity": "popular"},
    {"id": "cecil", "name": "Cecil", "gender": "male", "origins": ["latin"], "styles": ["vintage", "gentle"], "meaning": "Blind", "popularity": "uncommon"},
    {"id": "cedric", "name": "Cedric", "gender": "male", "origins": ["celtic"], "styles": ["classic", "royal"], "meaning": "Bounty", "popularity": "uncommon"},
    {"id": "cesar", "name": "Cesar", "gender": "male", "origins": ["spanish"], "styles": ["classic", "royal"], "meaning": "Long-haired", "popularity": "common"},
    {"id": "chad", "name": "Chad", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Battle warrior", "popularity": "common"},
    {"id": "chance", "name": "Chance", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Good fortune", "popularity": "common"},
    {"id": "chandler", "name": "Chandler", "gender": "neutral", "origins": ["english"], "styles": ["modern", "trendy"], "meaning": "Candle maker", "popularity": "common"},
    {"id": "charles", "name": "Charles", "gender": "male", "origins": ["german"], "styles": ["classic", "royal"], "meaning": "Free man", "popularity": "popular"},
    {"id": "charlie", "name": "Charlie", "gender": "neutral", "origins": ["english"], "styles": ["modern", "gentle"], "meaning": "Free man", "popularity": "popular"},
    {"id": "chase", "name": "Chase", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "To hunt", "popularity": "popular"},
    {"id": "chester", "name": "Chester", "gender": "male", "origins": ["english"], "styles": ["vintage", "gentle"], "meaning": "Fortress", "popularity": "uncommon"},
    {"id": "christian", "name": "Christian", "gender": "male", "origins": ["latin"], "styles": ["classic", "religious"], "meaning": "Follower of Christ", "popularity": "popular"},
    {"id": "clark", "name": "Clark", "gender": "male", "origins": ["english"], "styles": ["classic", "strong"], "meaning": "Clerk", "popularity": "common"},
    {"id": "clay", "name": "Clay", "gender": "male", "origins": ["english"], "styles": ["modern", "nature"], "meaning": "Clay maker", "popularity": "common"},
    {"id": "clayton", "name": "Clayton", "gender": "male", "origins": ["english"], "styles": ["classic", "strong"], "meaning": "Clay settlement", "popularity": "popular"},
    {"id": "clement", "name": "Clement", "gender": "male", "origins": ["latin"], "styles": ["vintage", "gentle"], "meaning": "Merciful", "popularity": "uncommon"},
    {"id": "clifford", "name": "Clifford", "gender": "male", "origins": ["english"], "styles": ["vintage", "strong"], "meaning": "Ford by a cliff", "popularity": "uncommon"},
    {"id": "clint", "name": "Clint", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Hilltop town", "popularity": "common"},
    {"id": "clinton", "name": "Clinton", "gender": "male", "origins": ["english"], "styles": ["classic", "strong"], "meaning": "Hilltop town", "popularity": "common"},
    {"id": "clyde", "name": "Clyde", "gender": "male", "origins": ["scottish"], "styles": ["vintage", "strong"], "meaning": "Warm", "popularity": "uncommon"},
    {"id": "cody", "name": "Cody", "gender": "male", "origins": ["irish"], "styles": ["modern", "strong"], "meaning": "Helpful", "popularity": "popular"},
    {"id": "colby", "name": "Colby", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Coal town", "popularity": "popular"},
    {"id": "cole", "name": "Cole", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Coal black", "popularity": "popular"},
    {"id": "coleman", "name": "Coleman", "gender": "male", "origins": ["irish"], "styles": ["classic", "strong"], "meaning": "Dove", "popularity": "uncommon"},
    {"id": "colin", "name": "Colin", "gender": "male", "origins": ["irish"], "styles": ["classic", "gentle"], "meaning": "Young creature", "popularity": "popular"},
    {"id": "collin", "name": "Collin", "gender": "male", "origins": ["irish"], "styles": ["modern", "gentle"], "meaning": "Young creature", "popularity": "popular"},
    {"id": "colson", "name": "Colson", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Son of Nicholas", "popularity": "uncommon"},
    {"id": "colt", "name": "Colt", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Young horse", "popularity": "uncommon"},
    {"id": "colten", "name": "Colten", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Coal town", "popularity": "common"},
    {"id": "colton", "name": "Colton", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Coal town", "popularity": "popular"},
    {"id": "conner", "name": "Conner", "gender": "male", "origins": ["irish"], "styles": ["modern", "strong"], "meaning": "Lover of hounds", "popularity": "popular"},
    {"id": "connor", "name": "Connor", "gender": "male", "origins": ["irish"], "styles": ["modern", "strong"], "meaning": "Lover of hounds", "popularity": "popular"},
    {"id": "conrad", "name": "Conrad", "gender": "male", "origins": ["german"], "styles": ["vintage", "strong"], "meaning": "Brave counsel", "popularity": "uncommon"},
    {"id": "cooper", "name": "Cooper", "gender": "male", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Barrel maker", "popularity": "popular"},
    {"id": "corbin", "name": "Corbin", "gender": "male", "origins": ["latin"], "styles": ["modern", "strong"], "meaning": "Raven", "popularity": "common"},
    {"id": "corey", "name": "Corey", "gender": "neutral", "origins": ["irish"], "styles": ["modern", "gentle"], "meaning": "Hollow", "popularity": "common"},
    {"id": "cornelius", "name": "Cornelius", "gender": "male", "origins": ["latin"], "styles": ["vintage", "royal"], "meaning": "Horn", "popularity": "uncommon"},
    {"id": "cory", "name": "Cory", "gender": "neutral", "origins": ["irish"], "styles": ["modern", "gentle"], "meaning": "Hollow", "popularity": "common"},
    {"id": "craig", "name": "Craig", "gender": "male", "origins": ["scottish"], "styles": ["modern", "strong"], "meaning": "Rock", "popularity": "common"},
    {"id": "crew", "name": "Crew", "gender": "male", "origins": ["english"], "styles": ["modern", "trendy"], "meaning": "Group", "popularity": "uncommon"},
    {"id": "cristian", "name": "Cristian", "gender": "male", "origins": ["latin"], "styles": ["classic", "religious"], "meaning": "Follower of Christ", "popularity": "popular"},
    {"id": "crosby", "name": "Crosby", "gender": "male", "origins": ["irish"], "styles": ["vintage", "literary"], "meaning": "Village with crosses", "popularity": "uncommon"},
    {"id": "cruz", "name": "Cruz", "gender": "neutral", "origins": ["spanish"], "styles": ["modern", "strong"], "meaning": "Cross", "popularity": "popular"},
    {"id": "cullen", "name": "Cullen", "gender": "male", "origins": ["irish"], "styles": ["modern", "strong"], "meaning": "Handsome", "popularity": "uncommon"},
    {"id": "curtis", "name": "Curtis", "gender": "male", "origins": ["french"], "styles": ["classic", "strong"], "meaning": "Courteous", "popularity": "common"},
    {"id": "cyrus", "name": "Cyrus", "gender": "male", "origins": ["persian"], "styles": ["classic", "royal"], "meaning": "Sun", "popularity": "common"},
]

# I'll continue with more names, but this gives you the pattern
# Adding significant female names
female_names = [
    # A
    {"id": "aaliyah", "name": "Aaliyah", "gender": "female", "origins": ["arabic"], "styles": ["modern", "elegant"], "meaning": "Exalted", "popularity": "popular"},
    {"id": "abbey", "name": "Abbey", "gender": "female", "origins": ["hebrew"], "styles": ["modern", "gentle"], "meaning": "Father's joy", "popularity": "common"},
    {"id": "abby", "name": "Abby", "gender": "female", "origins": ["hebrew"], "styles": ["modern", "gentle"], "meaning": "Father's joy", "popularity": "popular"},
    {"id": "abigail", "name": "Abigail", "gender": "female", "origins": ["hebrew"], "styles": ["biblical", "classic"], "meaning": "Father's joy", "popularity": "popular"},
    {"id": "ada", "name": "Ada", "gender": "female", "origins": ["german"], "styles": ["vintage", "gentle"], "meaning": "Noble", "popularity": "common"},
    {"id": "adair", "name": "Adair", "gender": "neutral", "origins": ["scottish"], "styles": ["vintage", "strong"], "meaning": "Oak tree ford", "popularity": "rare"},
    {"id": "adaline", "name": "Adaline", "gender": "female", "origins": ["german"], "styles": ["vintage", "elegant"], "meaning": "Noble", "popularity": "common"},
    {"id": "addelyn", "name": "Addelyn", "gender": "female", "origins": ["english"], "styles": ["modern", "trendy"], "meaning": "Noble", "popularity": "common"},
    {"id": "adele", "name": "Adele", "gender": "female", "origins": ["german"], "styles": ["vintage", "elegant"], "meaning": "Noble", "popularity": "common"},
    {"id": "adeline", "name": "Adeline", "gender": "female", "origins": ["french"], "styles": ["vintage", "elegant"], "meaning": "Noble", "popularity": "popular"},
    {"id": "adriana", "name": "Adriana", "gender": "female", "origins": ["latin"], "styles": ["classic", "elegant"], "meaning": "From Hadria", "popularity": "popular"},
    {"id": "adrianna", "name": "Adrianna", "gender": "female", "origins": ["latin"], "styles": ["classic", "elegant"], "meaning": "From Hadria", "popularity": "popular"},
    {"id": "adrienne", "name": "Adrienne", "gender": "female", "origins": ["latin"], "styles": ["classic", "elegant"], "meaning": "From Hadria", "popularity": "common"},
    {"id": "agnes", "name": "Agnes", "gender": "female", "origins": ["greek"], "styles": ["vintage", "gentle"], "meaning": "Pure", "popularity": "uncommon"},
    {"id": "aida", "name": "Aida", "gender": "female", "origins": ["arabic"], "styles": ["classic", "artistic"], "meaning": "Returning", "popularity": "uncommon"},
    {"id": "aileen", "name": "Aileen", "gender": "female", "origins": ["irish"], "styles": ["classic", "gentle"], "meaning": "Light", "popularity": "common"},
    {"id": "aimee", "name": "Aimee", "gender": "female", "origins": ["french"], "styles": ["modern", "gentle"], "meaning": "Beloved", "popularity": "common"},
    {"id": "ainsley", "name": "Ainsley", "gender": "neutral", "origins": ["scottish"], "styles": ["modern", "trendy"], "meaning": "One's own meadow", "popularity": "popular"},
    {"id": "aisha", "name": "Aisha", "gender": "female", "origins": ["arabic"], "styles": ["classic", "elegant"], "meaning": "Living", "popularity": "common"},
    {"id": "alayna", "name": "Alayna", "gender": "female", "origins": ["irish"], "styles": ["modern", "gentle"], "meaning": "Fair", "popularity": "common"},
    {"id": "aleah", "name": "Aleah", "gender": "female", "origins": ["hebrew"], "styles": ["modern", "gentle"], "meaning": "Ascending", "popularity": "uncommon"},
    {"id": "aleena", "name": "Aleena", "gender": "female", "origins": ["irish"], "styles": ["modern", "gentle"], "meaning": "Fair", "popularity": "uncommon"},
    {"id": "alejandra", "name": "Alejandra", "gender": "female", "origins": ["spanish"], "styles": ["classic", "strong"], "meaning": "Defender", "popularity": "popular"},
    {"id": "alessa", "name": "Alessa", "gender": "female", "origins": ["italian"], "styles": ["modern", "elegant"], "meaning": "Defender", "popularity": "uncommon"},
    {"id": "alessandra", "name": "Alessandra", "gender": "female", "origins": ["italian"], "styles": ["classic", "elegant"], "meaning": "Defender", "popularity": "common"},
    {"id": "alessia", "name": "Alessia", "gender": "female", "origins": ["italian"], "styles": ["modern", "elegant"], "meaning": "Defender", "popularity": "uncommon"},
    {"id": "alexa", "name": "Alexa", "gender": "female", "origins": ["greek"], "styles": ["modern", "strong"], "meaning": "Defender", "popularity": "popular"},
    {"id": "alexandra", "name": "Alexandra", "gender": "female", "origins": ["greek"], "styles": ["classic", "royal"], "meaning": "Defender", "popularity": "popular"},
    {"id": "alexandria", "name": "Alexandria", "gender": "female", "origins": ["greek"], "styles": ["classic", "elegant"], "meaning": "Defender", "popularity": "popular"},
    {"id": "alexia", "name": "Alexia", "gender": "female", "origins": ["greek"], "styles": ["modern", "strong"], "meaning": "Defender", "popularity": "common"},
    {"id": "alexis", "name": "Alexis", "gender": "neutral", "origins": ["greek"], "styles": ["modern", "strong"], "meaning": "Defender", "popularity": "popular"},
    {"id": "alice", "name": "Alice", "gender": "female", "origins": ["german"], "styles": ["vintage", "literary"], "meaning": "Noble", "popularity": "popular"},
    {"id": "alicia", "name": "Alicia", "gender": "female", "origins": ["spanish"], "styles": ["classic", "elegant"], "meaning": "Noble", "popularity": "popular"},
    {"id": "alina", "name": "Alina", "gender": "female", "origins": ["slavic"], "styles": ["modern", "elegant"], "meaning": "Bright", "popularity": "popular"},
    {"id": "alison", "name": "Alison", "gender": "female", "origins": ["german"], "styles": ["classic", "gentle"], "meaning": "Noble", "popularity": "popular"},
    {"id": "aliyah", "name": "Aliyah", "gender": "female", "origins": ["hebrew"], "styles": ["modern", "elegant"], "meaning": "Exalted", "popularity": "popular"},
    {"id": "allie", "name": "Allie", "gender": "female", "origins": ["english"], "styles": ["modern", "gentle"], "meaning": "Noble", "popularity": "popular"},
    {"id": "allison", "name": "Allison", "gender": "female", "origins": ["english"], "styles": ["classic", "gentle"], "meaning": "Noble", "popularity": "popular"},
    {"id": "alma", "name": "Alma", "gender": "female", "origins": ["latin"], "styles": ["vintage", "gentle"], "meaning": "Nourishing", "popularity": "common"},
    {"id": "alondra", "name": "Alondra", "gender": "female", "origins": ["spanish"], "styles": ["modern", "nature"], "meaning": "Lark", "popularity": "common"},
    {"id": "althea", "name": "Althea", "gender": "female", "origins": ["greek"], "styles": ["vintage", "literary"], "meaning": "Healing", "popularity": "uncommon"},
    {"id": "alyssa", "name": "Alyssa", "gender": "female", "origins": ["greek"], "styles": ["modern", "gentle"], "meaning": "Noble", "popularity": "popular"},
    {"id": "amara", "name": "Amara", "gender": "female", "origins": ["african"], "styles": ["modern", "elegant"], "meaning": "Grace", "popularity": "common"},
    {"id": "amber", "name": "Amber", "gender": "female", "origins": ["english"], "styles": ["modern", "nature"], "meaning": "Jewel", "popularity": "popular"},
    {"id": "amberly", "name": "Amberly", "gender": "female", "origins": ["english"], "styles": ["modern", "gentle"], "meaning": "Jewel meadow", "popularity": "uncommon"},
    {"id": "amelie", "name": "Amelie", "gender": "female", "origins": ["french"], "styles": ["vintage", "elegant"], "meaning": "Hardworking", "popularity": "common"},
    {"id": "america", "name": "America", "gender": "female", "origins": ["english"], "styles": ["modern", "strong"], "meaning": "Home ruler", "popularity": "uncommon"},
    {"id": "ami", "name": "Ami", "gender": "female", "origins": ["french"], "styles": ["modern", "gentle"], "meaning": "Friend", "popularity": "uncommon"},
    {"id": "amira", "name": "Amira", "gender": "female", "origins": ["arabic"], "styles": ["modern", "royal"], "meaning": "Princess", "popularity": "common"},
    {"id": "amy", "name": "Amy", "gender": "female", "origins": ["french"], "styles": ["classic", "gentle"], "meaning": "Beloved", "popularity": "popular"},
    {"id": "ana", "name": "Ana", "gender": "female", "origins": ["spanish"], "styles": ["classic", "gentle"], "meaning": "Grace", "popularity": "popular"},
    {"id": "anabel", "name": "Anabel", "gender": "female", "origins": ["spanish"], "styles": ["vintage", "elegant"], "meaning": "Lovable", "popularity": "uncommon"},
    {"id": "anabella", "name": "Anabella", "gender": "female", "origins": ["italian"], "styles": ["classic", "elegant"], "meaning": "Lovable", "popularity": "common"},
    {"id": "anabelle", "name": "Anabelle", "gender": "female", "origins": ["french"], "styles": ["vintage", "elegant"], "meaning": "Lovable", "popularity": "common"},
    {"id": "anastasia", "name": "Anastasia", "gender": "female", "origins": ["greek"], "styles": ["classic", "royal"], "meaning": "Resurrection", "popularity": "popular"},
    {"id": "andrea", "name": "Andrea", "gender": "neutral", "origins": ["greek"], "styles": ["classic", "strong"], "meaning": "Brave", "popularity": "popular"},
    {"id": "angel", "name": "Angel", "gender": "neutral", "origins": ["greek"], "styles": ["modern", "spiritual"], "meaning": "Messenger", "popularity": "popular"},
    {"id": "angela", "name": "Angela", "gender": "female", "origins": ["greek"], "styles": ["classic", "gentle"], "meaning": "Messenger", "popularity": "popular"},
    {"id": "angelica", "name": "Angelica", "gender": "female", "origins": ["latin"], "styles": ["classic", "elegant"], "meaning": "Angelic", "popularity": "common"},
    {"id": "angelina", "name": "Angelina", "gender": "female", "origins": ["italian"], "styles": ["classic", "elegant"], "meaning": "Angel", "popularity": "popular"},
    {"id": "angie", "name": "Angie", "gender": "female", "origins": ["greek"], "styles": ["modern", "gentle"], "meaning": "Messenger", "popularity": "common"},
    {"id": "anika", "name": "Anika", "gender": "female", "origins": ["scandinavian"], "styles": ["modern", "gentle"], "meaning": "Grace", "popularity": "uncommon"},
    {"id": "anita", "name": "Anita", "gender": "female", "origins": ["spanish"], "styles": ["vintage", "gentle"], "meaning": "Grace", "popularity": "common"},
    {"id": "ann", "name": "Ann", "gender": "female", "origins": ["hebrew"], "styles": ["classic", "gentle"], "meaning": "Grace", "popularity": "popular"},
    {"id": "anna", "name": "Anna", "gender": "female", "origins": ["hebrew"], "styles": ["classic", "gentle"], "meaning": "Grace", "popularity": "popular"},
    {"id": "annabel", "name": "Annabel", "gender": "female", "origins": ["scottish"], "styles": ["vintage", "elegant"], "meaning": "Lovable", "popularity": "common"},
    {"id": "annabella", "name": "Annabella", "gender": "female", "origins": ["italian"], "styles": ["classic", "elegant"], "meaning": "Lovable", "popularity": "uncommon"},
    {"id": "annabelle", "name": "Annabelle", "gender": "female", "origins": ["french"], "styles": ["vintage", "elegant"], "meaning": "Lovable", "popularity": "popular"},
    {"id": "anne", "name": "Anne", "gender": "female", "origins": ["hebrew"], "styles": ["classic", "gentle"], "meaning": "Grace", "popularity": "popular"},
    {"id": "annette", "name": "Annette", "gender": "female", "origins": ["french"], "styles": ["vintage", "gentle"], "meaning": "Grace", "popularity": "common"},
    {"id": "annie", "name": "Annie", "gender": "female", "origins": ["hebrew"], "styles": ["vintage", "gentle"], "meaning": "Grace", "popularity": "popular"},
    {"id": "annika", "name": "Annika", "gender": "female", "origins": ["scandinavian"], "styles": ["modern", "gentle"], "meaning": "Grace", "popularity": "common"},
    {"id": "ansley", "name": "Ansley", "gender": "female", "origins": ["english"], "styles": ["modern", "trendy"], "meaning": "Hermitage field", "popularity": "common"},
    {"id": "antonia", "name": "Antonia", "gender": "female", "origins": ["latin"], "styles": ["classic", "elegant"], "meaning": "Priceless", "popularity": "common"},
    {"id": "april", "name": "April", "gender": "female", "origins": ["latin"], "styles": ["nature", "gentle"], "meaning": "Opening", "popularity": "common"},
    {"id": "arabella", "name": "Arabella", "gender": "female", "origins": ["latin"], "styles": ["vintage", "elegant"], "meaning": "Yielding to prayer", "popularity": "common"},
    {"id": "ariadne", "name": "Ariadne", "gender": "female", "origins": ["greek"], "styles": ["mythological", "elegant"], "meaning": "Most holy", "popularity": "uncommon"},
    {"id": "ariana", "name": "Ariana", "gender": "female", "origins": ["greek"], "styles": ["modern", "elegant"], "meaning": "Most holy", "popularity": "popular"},
    {"id": "arianna", "name": "Arianna", "gender": "female", "origins": ["italian"], "styles": ["modern", "elegant"], "meaning": "Most holy", "popularity": "popular"},
    {"id": "ariel", "name": "Ariel", "gender": "neutral", "origins": ["hebrew"], "styles": ["modern", "mystical"], "meaning": "Lion of God", "popularity": "popular"},
    {"id": "ariella", "name": "Ariella", "gender": "female", "origins": ["hebrew"], "styles": ["modern", "elegant"], "meaning": "Lion of God", "popularity": "common"},
    {"id": "arielle", "name": "Arielle", "gender": "female", "origins": ["french"], "styles": ["modern", "elegant"], "meaning": "Lion of God", "popularity": "common"},
    {"id": "arlene", "name": "Arlene", "gender": "female", "origins": ["irish"], "styles": ["vintage", "gentle"], "meaning": "Pledge", "popularity": "uncommon"},
    {"id": "armani", "name": "Armani", "gender": "neutral", "origins": ["italian"], "styles": ["modern", "trendy"], "meaning": "Warrior", "popularity": "uncommon"},
    {"id": "artemis", "name": "Artemis", "gender": "neutral", "origins": ["greek"], "styles": ["mythological", "strong"], "meaning": "Safe", "popularity": "uncommon"},
    {"id": "ashley", "name": "Ashley", "gender": "neutral", "origins": ["english"], "styles": ["modern", "gentle"], "meaning": "Ash tree meadow", "popularity": "popular"},
    {"id": "ashlyn", "name": "Ashlyn", "gender": "female", "origins": ["irish"], "styles": ["modern", "gentle"], "meaning": "Dream", "popularity": "popular"},
    {"id": "ashlynn", "name": "Ashlynn", "gender": "female", "origins": ["irish"], "styles": ["modern", "gentle"], "meaning": "Dream", "popularity": "popular"},
    {"id": "athena", "name": "Athena", "gender": "female", "origins": ["greek"], "styles": ["mythological", "strong"], "meaning": "Goddess of wisdom", "popularity": "popular"},
    {"id": "aubree", "name": "Aubree", "gender": "female", "origins": ["french"], "styles": ["modern", "gentle"], "meaning": "Elf ruler", "popularity": "popular"},
    {"id": "aubrey", "name": "Aubrey", "gender": "neutral", "origins": ["french"], "styles": ["modern", "gentle"], "meaning": "Elf ruler", "popularity": "popular"},
    {"id": "aubrianna", "name": "Aubrianna", "gender": "female", "origins": ["french"], "styles": ["modern", "elegant"], "meaning": "Elf ruler", "popularity": "uncommon"},
    {"id": "aubrielle", "name": "Aubrielle", "gender": "female", "origins": ["french"], "styles": ["modern", "elegant"], "meaning": "Elf ruler", "popularity": "uncommon"},
    {"id": "audra", "name": "Audra", "gender": "female", "origins": ["english"], "styles": ["vintage", "strong"], "meaning": "Noble strength", "popularity": "uncommon"},
    {"id": "audrey", "name": "Audrey", "gender": "female", "origins": ["english"], "styles": ["vintage", "elegant"], "meaning": "Noble strength", "popularity": "popular"},
    {"id": "audrina", "name": "Audrina", "gender": "female", "origins": ["english"], "styles": ["modern", "elegant"], "meaning": "Noble strength", "popularity": "uncommon"},
    {"id": "aurora", "name": "Aurora", "gender": "female", "origins": ["latin"], "styles": ["mythological", "elegant"], "meaning": "Dawn", "popularity": "popular"},
    {"id": "autumn", "name": "Autumn", "gender": "female", "origins": ["latin"], "styles": ["nature", "gentle"], "meaning": "Fall season", "popularity": "popular"},
    {"id": "avalyn", "name": "Avalyn", "gender": "female", "origins": ["english"], "styles": ["modern", "elegant"], "meaning": "Beautiful bird", "popularity": "uncommon"},
    {"id": "averie", "name": "Averie", "gender": "neutral", "origins": ["english"], "styles": ["modern", "gentle"], "meaning": "Elf ruler", "popularity": "common"},
    {"id": "aviana", "name": "Aviana", "gender": "female", "origins": ["latin"], "styles": ["modern", "elegant"], "meaning": "Like a bird", "popularity": "uncommon"},
    {"id": "ayla", "name": "Ayla", "gender": "female", "origins": ["hebrew"], "styles": ["modern", "gentle"], "meaning": "Oak tree", "popularity": "popular"},
    {"id": "aylin", "name": "Aylin", "gender": "female", "origins": ["turkish"], "styles": ["modern", "gentle"], "meaning": "Moon halo", "popularity": "common"},
    {"id": "azalea", "name": "Azalea", "gender": "female", "origins": ["greek"], "styles": ["nature", "elegant"], "meaning": "Dry earth", "popularity": "uncommon"},
]

# Combine all names
all_new_names = male_names + female_names

# Get existing name IDs to avoid duplicates
existing_ids = {name['id'] for name in existing_names}
unique_new_names = [name for name in all_new_names if name['id'] not in existing_ids]

# Combine with existing
final_names = existing_names + unique_new_names

# Sort alphabetically
final_names.sort(key=lambda x: x['name'].lower())

# Write to file
with open('/Users/jdecker/projects/ios/name/NameMatch/Resources/names.json', 'w') as f:
    json.dump(final_names, f, indent=2)

print(f"Database expanded from {len(existing_names)} to {len(final_names)} names")
print(f"Added {len(unique_new_names)} new unique names")
print(f"\nBreakdown:")
print(f"  Male names added: {len([n for n in unique_new_names if n['gender'] == 'male'])}")
print(f"  Female names added: {len([n for n in unique_new_names if n['gender'] == 'female'])}")
print(f"  Neutral names added: {len([n for n in unique_new_names if n['gender'] == 'neutral'])}")
