name: Babinder
options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.1.0"
    CURRENT_PROJECT_VERSION: "2"
    INFOPLIST_KEY_CFBundleDisplayName: "Babinder"

targets:
  NameMatch:
    type: application
    platform: iOS
    sources:
      - path: NameMatch
        excludes:
          - "**/.DS_Store"
    resources:
      - path: NameMatch/Resources/names.json
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jacobdecker.NameMatch
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        DEVELOPMENT_TEAM: ""
    entitlements:
      path: NameMatch/NameMatch.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.jacobdecker.NameMatch
        com.apple.developer.icloud-services:
          - CloudKit
